# Generated by Django 4.0.3 on 2024-02-03 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('musician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_musician', to='polls.musician')),
            ],
        ),
    ]
