# Generated by Django 4.0.3 on 2024-02-03 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='zip',
            new_name='zipcode',
        ),
    ]
